---
title: "Charte déontologique du CS RFFLabs "
subtitle: "Lettre de Mission"
---




# Principes généraux:

## Indépendance

L’indépendance professionnelle et scientifique du CS RFFLabs à l’égard des instances ou services politiques et administratifs ou des opérateurs privés dans le développement, la production et la diffusion des connaissances, des produits et services est une condition essentielle de la crédibilité du CS. Il appartient aux membres de l'Équipe de coordination de veiller au respect de ce principe.

## Impartialité et objectivité

Les membres du CS exercent leurs missions en étant guidés par des considérations scientifiques et professionnelles, au service de l’intérêt général. Ils mettent à disposition du public les informations concernant les méthodes et procédures suivies dans le cadre des enquêtes, évaluations, analyses et recherches. Ils rendent publics leurs résultats et leurs productions en toute impartialité et objectivité.

## Intégrité
Le CS entend réaliser ses missions en l’absence de tout conflit d’intérêt susceptible d’influencer ses travaux et de remettre en cause son impartialité. Il veille à l’intégrité et à la réputation de ses agents dans leur activité professionnelle. Les membres du CS ne peuvent solliciter, accepter ou se faire promettre d’aucune source, ni directement, ni indirectement, des avantages matériels ou immatériels dont l’acceptation pourrait les mettre en conflit avec leurs obligations professionnelles. Ce devoir d’intégrité exclut toute complaisance, tout favoritisme, et toute ingérence dans l’exercice de leurs fonctions.

## Obligation de réserve /confidentialité /secret statistique
La liberté d’opinion et d’expression de chacun, y compris à l’extérieur du CS sur tout support et sur les réseaux sociaux, s’applique dans le cadre légal, avec une obligation de réserve, de confidentialité et de neutralité, ce qui impose notamment d’exprimer à chaque occasion, à quel titre, personnel ou institutionnel, se fait l’intervention. Tous les agents sont soumis en outre à une obligation de confidentialité au titre des données confidentielles auxquelles ils ont accès dans l’accomplissement de leur travail pour le compte du CS. Les chargés d’études et statisticiens se voient par ailleurs appliquer le principe du secret statistique prévu par le code de bonnes pratiques de la statistique européenne.

## Exactitude et fiabilité

Les données et analyses produites par le CS doivent répondre aux exigences d’exactitude et de fiabilité conformes à l’état de l’art dans les différentes disciplines mobilisées. Les travaux conduits par les chargés d’étude et de recherche doivent répondre aux règles fixées par la charte nationale de déontologie des métiers de la recherche (2015) : existence de protocoles de recherche permettant la reproductibilité des travaux ; conservation de tous les résultats bruts et de l’analyse de ceux-ci à des fins de vérification éventuelle ; conclusions fondées sur une analyse critique des résultats ; communication des résultats dans leur totalité de manière objective et honnête ; référencement explicite des sources lors de toute production, publication et communication scientifiques.


## Engagements particuliers

1.	La compétence du CS repose, entre autres, sur la formation initiale, l’expérience professionnelle de ses membres, notamment celle obtenue dans le cadre de programmes de recherche, sur les apports résultant des coopérations scientifiques et techniques avec d’autres organismes français et étrangers et sur la qualité des équipements. Afin de conserver un niveau de compétence suffisant pour réaliser au mieux les missions qui lui sont confiées, le CS assure périodiquement l’évaluation des compétences des membres de ses membres.
2.	Le CS prend soin de maintenir la qualité scientifique et technique qui contribue à sa réputation. Il s’attache ainsi à prendre en considération dans ses travaux les données (scientifiques ou techniques) disponibles et objectives. Pour satisfaire au respect d’une démarche scientifique générale, le CS établit ses résultats, autant que possible, sur la base d’une concertation collective et/ou de procédures de vérification et d’approbation. Dans les mêmes conditions, il confronte ses résultats avec d’autres organismes, que ce soit dans le cadre de coopérations scientifiques ou dans le cadre de débats scientifiques. Toute production du CS fait figurer en annexe les éléments de méthodologie employés.
3.	Les membres du CS s’emploient à mettre en œuvre les moyens adaptés à la réalisation de la mission confiée. Pour ce faire, avant d'accepter une mission, le CS examine, autant que nécessaire, la tâche à entreprendre en la situant dans son contexte et, le cas échéant, dans le cadre légal et normatif. En outre, le CS veille à n’accepter une mission qu’après avoir défini et rassemblé les moyens nécessaires tant internes qu’externes, pour répondre à la demande.
4.	Le CS est responsable de ses travaux dans les conditions et limites définies ci-après. Lors de la remise de ses résultats, le CS veille, autant que nécessaire, à rendre compte des incertitudes et limites qui les affectent. Les avis, recommandations, préconisations ou équivalents qui seraient portés par le CS dans le cadre des prestations qui lui sont confiées peuvent aider à la prise de décision. Étant donné la mission qui incombe au CS de par son décret de création, le CS n'intervient pas dans la prise de décision proprement dite. La responsabilité du CS ne peut se substituer à celle du décideur. Le CS établit son rapport au regard d'un objet défini de manière contractuelle. Toute utilisation d’extrait ou de note de synthèse qui dénaturerait le contenu et l’esprit du rapport ou tout usage du rapport dans son intégralité en dehors du cadre contractuel ne saurait engager la responsabilité du CS.
5.	Les membres du CS exercent leurs compétences et mettent leur expertise au service des membres du RFFLabs à titre bénévole et sans obtenir aucune sorte de rétribution en échange. Ils peuvent toutefois compter leurs heures de travail à titre bénévole comme des dons à une association d’intérêt général, dans la mesure du raisonnable et en informant le CA des montants concernés afin que ceux-ci soient inscrits dans la comptabilité de l’association. Ils peuvent également solliciter le remboursement de frais particuliers engagés par leurs travaux pour le compte du CS, sous réserve de présentation de justificatifs.
6.	Les membres du CS font preuve d'objectivité, d'impartialité et savent s'abstraire de leur appartenance éventuelle à un groupe de pensée ou à une famille spirituelle ou intellectuelle. Ils s'abstiennent de tout parti pris, préjugé, ou favoritisme. Ils suivent les évolutions scientifiques des outils et des méthodes. Ils échangent sur la production de savoirs avec d'autres professionnels du secteur de la recherche et des études.
7.	Les membres du CS doivent veiller à éviter tout conflit d’intérêt entre leur responsabilité au sein de ce conseil et leurs activités économiques privées. Les membres du CS s’engagent à signaler tout risque de conflit d’intérêt aux autres membres du CS et du CA, et plus largement, ils sont tenus à recenser et signaler toutes leurs activités scientifiques ou expertales (dans la limite des clauses de confidentialité) qui présentent un intérêt pour RFFLabs - cet engagement s’inscrit naturellement dans le cadre de leur mission de veille pour les membres de l’association.
8.	Les membres du CS s’engagent à respecter le cas échéant les demandes d’anonymat dans le cadre des études de terrain qu’ils sont amenés à conduire sur les sujets d’intérêt pour le réseau.
9.	Les membres du CS sont soumis à une obligation de confidentialité, aussi bien à l'extérieur qu'à l'intérieur du CS, au titre des données non publiques auxquelles ils ont accès dans l'accomplissement de leur travail pour le compte du CS. Cette obligation ne concerne pas les communications et interviews assurées avec l'accord du CA ou de l'Équipe de coordination.
10.	Tout manquement au respect de cette Charte entraine une exclusion du CS sur décision informée et instruite du CA de RFFLabs sur demande de l'Équipe de Coordination du CS ou de tout membre du réseau ayant pu avoir connaissance de cet éventuel manquement.
